### PR TITLE
Added function GetRelativeIncludeStatement

### PR DESCRIPTION
**Pull request by edgar79**
Hello,

I wrote this patch to automatically include the path to the LibreOffice-File.
Using this it would be easy to share external LilyPond-Files with the LibreOffice-File
without setting the include option manually for every file.

Mit freundlichen Grüßen und vielem Dank,
Hannes E. Schäuble

### CODE REVIEW

**Comment by KlausBlum** [comment]
Hello, 

thank you very much for your contribution. This is indeed a great idea, and I'd like to integrate your code into the next release. 

One remark: I'd like to change the order of the statements to 
`sIncludeStatement = sRelativeIncludeStatement & " " & sIncludeStatement`

With that, `sRelativeIncludeStatement` has priority over the other paths. 
That means, even if I have an include file with the same name in my default folder, LO will use the one from the document folder. 

What do you think?

Herzliche Grüße, 
Klaus Blum

**Comment by edgar79** [comment]
Hello,

your proposed change to increase the priority of the `sRelativeIncludeStatement` is a good idea too,
so I just pushed it into this branch.

Herzliche Grüße,
Hannes Schäuble

**Comment by KlausBlum** [comment]
Hi Hannes, 

that's a really cool and useful enhancement. Thanks again. 
I'll merge your branch into master. 

Cheers, 
Klaus

**Comment by KlausBlum** [comment]
Integrated into 0.5.9 Release: 
https://github.com/openlilylib/LO-ly/releases/tag/0.5.9

**Pull request merged**
